version: '3'
name: pony-market-dev
services:


  nestjs_app_dev:
    container_name: nestjs_app_dev
    restart: always
    build:
      context: ../../../pony market/backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../../backend:/home/src/app
      - /home/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db_dev

  db_dev:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_DEV}
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  pgdata_dev:
