version: '3'
name: pony-market-dev
services:

  adonis_app_dev:
    container_name: adonis_app_dev
    restart: always
    build:
      context: "../../backend-api/"
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    env_file:
      - "../../backend-api/.env"
    volumes:
      - ./:/home/node/app
    command:  node ace serve --watch --node-args="--inspect=0.0.0.0"
    depends_on:
      - db_dev

  db_dev:
    container_name: dev-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_DEV}
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
    ports:
      - "5433:5433"

  pgadmin_dev:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"

volumes:
  pgdata_dev:
